# -*- coding: utf-8 -*-
"""Keras_Image_Inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BF8UgtLm6PUd4fy-o9DMlyr5IVJzSDRn
"""

from keras.models import load_model
from keras.models import model_from_json
import json

def restoreModel(model_str):
    with open(model_str + ".json", "r") as f:
        model_json = json.load(f)

    model_restored = model_from_json(model_json)
    model_restored.load_weights(model_str + ".h5")
    model_restored.summary()
    return model_restored

import cv2
import numpy as np

def load_label_map(textFile):
    return np.loadtxt(textFile, str, delimiter='\t')
    
def cv_image_read(image_path):
    print(image_path)
    return cv2.imread(image_path)

def print_result(inference_result, class_map):
    class_text = class_map[np.argmax(inference_result)]
    print(inference_result)
    print(class_text)

def inference_image(opencv_image, model, size = (224, 224)):
    image = cv2.resize(opencv_image, size)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image_tensor = np.expand_dims(image, axis=0)
    result = model.predict(image_tensor)
    return result

def main(image_path):
    img_width, img_height = 224, 224
    class_map = load_label_map('label_map.txt')
    num_classes = len(class_map)

    model_str = "keras_Classification_Model"
    model = restoreModel(model_str)

    opencv_image = cv_image_read(image_path)
    inference_result = inference_image(opencv_image, model, (img_width, img_height))
    print_result(inference_result, class_map)

!wget https://storage.googleapis.com/mledu-datasets/cats_and_dogs_filtered.zip
!unzip -qq cats_and_dogs_filtered.zip

import os
PATH = "/content/cats_and_dogs_filtered/validation"
validation_cats_dir = PATH + '/cats'  # directory with our validation cat pictures
validation_dogs_dir = PATH + '/dogs'  # directory with our validation dog pictures
list_of_test_cats_images = os.listdir(validation_cats_dir)
list_of_test_dogs_images = os.listdir(validation_dogs_dir)
for idx in range(len(list_of_test_cats_images)):
    list_of_test_cats_images[idx] = validation_cats_dir + '/'+list_of_test_cats_images[idx]
for idx in range(len(list_of_test_dogs_images)):
    list_of_test_dogs_images[idx] = validation_dogs_dir + '/'+list_of_test_dogs_images[idx]
list_of_test_images = list_of_test_cats_images + list_of_test_dogs_images

main(list_of_test_images[500])

